.eqv VOICE_PIANO                0
.eqv VOICE_CHROMATIC_PERCUSSION 8
.eqv VOICE_ORGAN                16
.eqv VOICE_GUITAR               24
.eqv VOICE_BASS                 32
.eqv VOICE_STRINGS              40
.eqv VOICE_ENSEMBLE             48
.eqv VOICE_BRASS                56
.eqv VOICE_REED                 64
.eqv VOICE_PIPE                 72
.eqv VOICE_SYNTH_LEAD           80
.eqv VOICE_SYNTH_PAD            88
.eqv VOICE_SYNTH_EFFECTS        96
.eqv VOICE_ETHNIC               104
.eqv VOICE_PERCUSSION           112
.eqv VOICE_SOUND_EFFECTS        120